<?php

namespace App\Repository;

use Symfony\Component\Validator\Constraints\DateTime;

/**
 * TripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByDate()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT trip FROM App:Trip trip
                WHERE trip.departureTime > 2018-01-01 
                ORDER BY trip.departureTime ASC'
            )
            ->getResult();
    }
}
